avoids template recursion for and_ / or_
NVIDIA/thrust pull request #1352
Opened 2020-12-06 19:56 UTC by andrewcorrigan

Per feedback from @allisonvacanti, although it ended up being a significant compilation performance hazard, this avoids template recursion in the implementation of `and_` /  `or_`  for the case of `THRUST_CPP_DIALECT >= 2017`

2020-12-06 19:56 UTC, GPUtester commented
Can one of the admins verify this patch?

2020-12-09 19:29 UTC, allisonvacanti reviewed
LGTM -- I'll start testing soon.

2020-12-09 19:29 UTC, allisonvacanti commented
run tests

2020-12-09 19:32 UTC, allisonvacanti commented
Reminding myself to test locally since gpuCI hasn't enabled C++17 builds yet.

2020-12-09 19:34 UTC, allisonvacanti commented
DVS CL: 29407187

2021-01-01 03:38 UTC, brycelelbach requested changes
We already have code for this - see `thrust/type_traits/logical_metafunctions.h`, which has a backwards compatible implementation of C++17's `conjunction`, `disjunction`, and `negation`. I'd prefer to refactor code to use that instead.

2021-01-01 09:08 UTC, andrewcorrigan commented
Gotcha.   Thanks for taking a look at this.

2021-01-01 09:08 UTC, closed without merging