Allow thrust headers to be installed into a subdirectory of `include`
NVIDIA/thrust pull request #1584
Opened 2021-12-17 17:32 UTC by robertmaynard

Fixes #1541 

Requires CUB PR: https://github.com/NVIDIA/cub/pull/415

2021-12-17 21:12 UTC, robertmaynard commented
Thinking about this more I believe we can make this easier by removing the custom INFIX variable and instead allow the user to specify a custom `CMAKE_INSTALL_INCLUDEDIR` and propagate that during configuration of the installed viles

2021-12-20 14:54 UTC, robertmaynard commented
> Thinking about this more I believe we can make this easier by removing the custom INFIX variable and instead allow the user to specify a custom `CMAKE_INSTALL_INCLUDEDIR` and propagate that during configuration of the installed files

Updated the logic to install based on `CMAKE_INSTALL_INCLUDEDIR`. Not only did this make the logic easier to follow, it matches CMake best practises.

2022-01-10 17:43 UTC, allisonvacanti requested changes

2022-01-10 17:43 UTC, allisonvacanti commented on cmake/ThrustInstallRules.cmake
> +  DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
Add quotes around path.

2022-01-10 17:43 UTC, allisonvacanti commented on cmake/ThrustInstallRules.cmake
> +# Need to configure a file to store THRUST_INSTALL_HEADER_INFIX
Comment is outdated

2022-01-10 17:43 UTC, allisonvacanti commented on cmake/ThrustInstallRules.cmake
> +    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
Quotes

2022-01-10 17:43 UTC, allisonvacanti commented on thrust/cmake/thrust-config-version.cmake
> +include(${CMAKE_CURRENT_LIST_DIR}/thrust-header-search.cmake)
Quotes around path

2022-01-10 17:43 UTC, allisonvacanti commented on thrust/cmake/thrust-header-search.cmake
> +set_property(CACHE _THRUST_VERSION_INCLUDE_DIR PROPERTY TYPE INTERNAL)
Missing newline at EOF

2022-01-10 17:43 UTC, allisonvacanti commented on thrust/cmake/thrust-header-search.cmake
> +    ${CMAKE_CURRENT_LIST_DIR}/../..            # Source tree
Quotes

2022-01-10 17:43 UTC, allisonvacanti commented on thrust/cmake/thrust-header-search.cmake.in
> +    ${CMAKE_CURRENT_LIST_DIR}/../../../@CMAKE_INSTALL_INCLUDEDIR@
Quotes

2022-01-10 21:16 UTC, allisonvacanti commented
LGTM

run tests

2022-01-12 18:54 UTC, allisonvacanti approved these changes

2022-01-12 19:01 UTC, allisonvacanti commented
Last pushes just rebased and bumped the CUB submodule to resolve conflicts.

2022-01-12 19:01 UTC, merged