copy_if doesn't require copy assignment operator for OutputIterator
NVIDIA/thrust pull request #1756
Opened 2022-07-27 20:32 UTC by mfbalin

For OutputIterators who don't have copy assignment operator, the assignment into result was giving a compiler error. This change avoids using the copy assignment operator.

2022-07-27 20:32 UTC, GPUtester commented
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

2022-07-27 20:37 UTC, allisonvacanti requested changes
The change looks reasonable, but go ahead and remove the `return` statement following the `THRUST_CDP_DISPATCH` macro -- compilers will flag that as unreachable code and emit warnings.

2022-07-27 20:51 UTC, allisonvacanti approved these changes

2022-07-27 20:51 UTC, allisonvacanti commented
run tests

2022-07-28 08:11 UTC, miscco approved these changes
Thanks a lot for that contribution! 🎉

2022-07-28 14:46 UTC, allisonvacanti commented
run tests

2022-07-28 19:04 UTC, merged