Emit diagnostics for device lambdas
NVIDIA/thrust pull request #1760
Opened 2022-08-04 20:24 UTC by senior-zero

2022-08-04 20:25 UTC, senior-zero commented
run tests

2022-08-04 20:46 UTC, allisonvacanti requested changes
We shouldn't use CUB headers outside of `thrust/system/cuda/`, as CUB is only a dependency when the CUDA backend is enabled.

Let's replicate the logic from CUB in Thrust's type_traits.h and use that instead.

2022-08-04 20:47 UTC, jrhemstad commented
All the logic is in `cuda::std::invoke_result` isn't it? Can't we just use `cuda::std::invoke_result` directly?

2022-08-04 21:18 UTC, senior-zero commented
> All the logic is in `cuda::std::invoke_result` isn't it? Can't we just use `cuda::std::invoke_result` directly?

Invoke result is C++17 feature. CUB wrapper switches to result of for previous dialects.

2022-08-04 21:21 UTC, jrhemstad commented
> Invoke result is C++17 feature. CUB wrapper switches to result of for previous dialects.

Can't we back port `cuda::std::invoke_result_t` to be available prior to C++17? 

It's just a library feature, and we already have back ported many Standard Library features in libcu++, e.g., https://github.com/NVIDIA/libcudacxx/pull/66

2022-08-04 21:55 UTC, allisonvacanti commented
> Can't we back port cuda::std::invoke_result_t to be available prior to C++17?

We'd need a libcu++ release by 8/15 to do this.

2022-08-05 06:24 UTC, miscco commented on thrust/iterator/detail/transform_input_output_iterator.inl
> +  using Value = cub::detail::invoke_result_t<InputFunction, iterator_value_type>;
```suggestion
  using Value = CUB_NS_QUALIFIER::detail::invoke_result_t<InputFunction, iterator_value_type>;
```

2022-08-05 06:24 UTC, miscco commented on thrust/iterator/detail/transform_input_output_iterator.inl
> +      , cub::detail::invoke_result_t<InputFunction, iterator_value_type>
```suggestion
      , CUB_NS_QUALIFIER::detail::invoke_result_t<InputFunction, iterator_value_type>
```

2022-08-05 08:56 UTC, senior-zero commented
run tests

2022-08-05 17:11 UTC, allisonvacanti approved these changes

2022-08-05 21:59 UTC, merged